# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='CustomerName',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='IcNum',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='pages',
            new_name='NumOrder',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publication_date',
            new_name='PickUpDate',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_type',
        ),
        migrations.AddField(
            model_name='book',
            name='CarTypes',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'HONDA'), (2, 'HILUX'), (3, 'TOYOTA')], null=True),
        ),
    ]
